name: storybook_toolkit
description: A storybook for Flutter widgets. Live preview of isolated widgets for faster development and showcase.
issue_tracker: https://github.com/StorybookToolkit/storybook_toolkit/issues
repository: https://github.com/StorybookToolkit/storybook_toolkit
version: 2.0.0-dev.4

topics:
  - storybook
  - widgetbook
  - widgets
  - toolkit

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  go_router: ">=14.2.7 <17.0.0"
  inspector: ">=2.1.0 <3.0.0"
  pointer_interceptor: ^0.10.1+2
  syntax_highlight: ^0.5.0
  provider: ^6.1.2
  vader_popup: ^0.2.0
  device_frame_plus: ^1.3.0
  collection: ^1.18.0
  nested: ^1.0.0

dev_dependencies:
  mocktail: ^1.0.4
  flutter_lints: ">=5.0.0 <7.0.0"

flutter:
  uses-material-design: true
  assets:
    - assets/
